language: ruby
cache: bundler
rvm:
  - 2.2.2
env:
  - RAILS_ENV=test
before_install:
  - gem install bundler
script: 'bundle exec rspec spec'
notifications:
  slack:
    secure: EPBywkl2okI3plSIYdeU0ZpONAJMabRJ6l4lkHb4ZF0ccx/dnPvLxwcN7TLbTTRCBveith20ZKiOFuq7HG/ZLRjw8v+ffdbdFYe0Vvw9u3gXCaxCqpWS7UnZ5C66x5jyOsgOpQitzJ0p+qtIzG+/lOdv5hP5lOXKWpjWw2nBsxfDzuEG+jd0hqX2hwusy4AYZq4/rCzWqNlMNgme49mpX+CnlZSQW20LFPSlhhA9VvW6ZlIwZK04uhOG5TzwAODYdP4+yFVm99BFjlNR4wKRi/jy9b33yZodK0ScdKepU58JU99e2OxxoqJX7zoCLPOyO/yCVA8S9oQXdft/Ij1OawIA+6pX5YWaUWEtdMD/ksX8SNe9OWtIaBSIjnhhStpL6/nN3oWKmhxoVBmt6KaYUaZEGTflKiFAtkrMjqKnsnJHn2x7kb0kqEJ8p1dQ5ungVn3sqkZBDlP+x2nGfp/xgQ1oSmb7HsBcIJNA93BjraKdQeJiONGrg0ywT3hYgDVDAR1JCLIP97vNT5auih3rSwQOJAhbf++2Lpm+AZXW8AYIquSnUb7epkn5kK3vajmJvaiR8WpdmnvODuFsDn4W0TghEFqA13R19nSnYa8TP4/Gauj1dZPPSXe2ylP1aAHFAAl2CTnPowfhopHt2ZcL7WPPwnsq88+Vtg/3rm+wqgs=
